package br.pucminas.progmod.sistemabiblioteca.enums;

public enum CategoriaNome {
	GENERALIDADES,
	FILOSOFIA,
	PSICOLOGIA,
	RELIGIAO,
	CIENCIAS_SOCIAIS,
	LINGUAS,
	CIENCIAS_NATURAIS,
	MATEMATICA,
	TECNOLOGIA,
	CIENCIAS_APLICADAS,
	ARTES,
	LITERATURA,
	GEOGRAFIA,
	HISTORIA
}
